#Created by st.Game
#https://github.com/andrii1890
#Find me at Discord: st_Game and Telegram: @Andrii1890

#Version "1.0"

services:
  # 
  #░██████╗░███████╗████████╗██╗░░██╗
  # ██╔════╝░██╔════╝╚══██╔══╝██║░░██║
  # ██║░░██╗░█████╗░░░░░██║░░░███████║
  # ██║░░╚██╗██╔══╝░░░░░██║░░░██╔══██║
  # ╚██████╔╝███████╗░░░██║░░░██║░░██║
  #░╚═════╝░╚══════╝░░░╚═╝░░░╚═╝░░╚═╝

  geth:
    image: ethereum/client-go:latest
    ports:
      - ${GETH_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${GETH_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${GETH_PORT:-8545}:8545/tcp
      - ${WS_PORT:-8546}:8546/tcp
    command: |
      --sepolia
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts=*
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins="*"
      --http.api=admin,web3,eth,txpool,net
      --ws.api=admin,web3,eth,txpool,net
      --authrpc.jwtsecret=/root/jwt/jwt.hex
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
      --metrics.influxdb
      --metrics.influxdb.endpoint=http://influxdb:8086
      --metrics.influxdb.username=admin
      --metrics.influxdb.password=admin
    networks: [node]
    volumes:
      - ./data/geth:/root/.ethereum
      - ./jwt:/root/jwt
    stop_grace_period: 3m # long grace period to avoid unclean shutdown
    restart: unless-stopped

  
  prysm:
    image: prysmaticlabs/prysm-beacon-chain:stable
    ports:
      - 13000:13000/tcp   # P2P TCP
      - 12000:12000/udp   # P2P UDP
      - 4000:4000/tcp     # HTTP Port
      - 3500:3500         # RPC Prot
      - 5054:5054         # Monitoring Port
    command: |
      --sepolia
      --checkpoint-sync-url=https://sepolia.beaconstate.info
      --genesis-beacon-api-url=https://sepolia.beaconstate.info
      --execution-endpoint=http://geth:8551
      --jwt-secret=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --monitoring-port=5054
      --accept-terms-of-use=true  
    networks: [node]
    volumes:
      - ./data/prysm:/opt/app/beacon
      - ./jwt:/opt/jwt
    stop_grace_period: 3m # long grace period to avoid unclean shutdown
    restart: unless-stopped

  # 
  # ██╗███╗░░██╗███████╗██╗░░░░░██╗░░░██╗██╗░░██╗██████╗░██████╗░
  # ██║████╗░██║██╔════╝██║░░░░░██║░░░██║╚██╗██╔╝██╔══██╗██╔══██╗
  # ██║██╔██╗██║█████╗░░██║░░░░░██║░░░██║░╚███╔╝░██║░░██║██████╦
  # ██║██║╚████║██╔══╝░░██║░░░░░██║░░░██║░██╔██╗░██║░░██║██╔══██╗
  # ██║██║░╚███║██║░░░░░███████╗╚██████╔╝██╔╝╚██╗██████╔╝██████╦╝
  # ╚═╝╚═╝░░╚══╝╚═╝░░░░░╚══════╝░╚═════╝░╚═╝░░╚═╝╚═════╝░╚═════╝░
  #

  influxdb:
    image: influxdb:1.8.9
    hostname: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=geth
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=admin
    networks: [node]
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: unless-stopped

  #  
  # ███╗░░░███╗░█████╗░███╗░░██╗██╗████████╗░█████╗░██████╗░██╗███╗░░██╗░██████╗░
  # ████╗░████║██╔══██╗████╗░██║██║╚══██╔══╝██╔══██╗██╔══██╗██║████╗░██║██╔════╝░
  # ██╔████╔██║██║░░██║██╔██╗██║██║░░░██║░░░██║░░██║██████╔╝██║██╔██╗██║██║░░██╗░
  # ██║╚██╔╝██║██║░░██║██║╚████║██║░░░██║░░░██║░░██║██╔══██╗██║██║╚████║██║░░╚██╗
  # ██║░╚═╝░██║╚█████╔╝██║░╚███║██║░░░██║░░░╚█████╔╝██║░░██║██║██║░╚███║╚██████╔╝
  # ╚═╝░░░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.44.0}
    user: ":"
    networks: [node]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    user: ":"
    ports:
      - ${MONITORING_PORT_GRAFANA:-3000}:3000
    networks: [node]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/dashboards/sepolia_dashboard.json"
    restart: unless-stopped
  loki:
    image: grafana/loki:2.8.0
    hostname: loki
    ports:
      - ${LOKI_PORT:-3200}:3200
    networks: [node]
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    restart: unless-stopped
  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    command: |
      --config.file=/etc/promtail/config.yml
      --config.expand-env=true
    networks: [node]
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-v1.6.0}
    ports:
      - "9200:9200"
    networks: [node]
    restart: unless-stopped
    
networks:
  node:
